/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shxyke.touchevent;

import com.shxyke.touchevent.wrappers.ServiceManager;
import com.shxyke.touchevent.wrappers.DisplayManager;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Queue;
import java.util.concurrent.LinkedBlockingQueue;


public class App {

    private static final BufferedReader STDIN = new BufferedReader(new InputStreamReader(System.in));
    private static final ServiceManager SERVICE_MANAGER = new ServiceManager();
    private static final Controller CONTROLLER = new Controller(SERVICE_MANAGER);
    private static final DisplayManager DISPLAY_MANAGER = SERVICE_MANAGER.getDisplayManager();
    private static final LinkedBlockingQueue<Queue<ControlMessage>> QUEUE = new LinkedBlockingQueue<>();

    public String getGreeting(DisplayInfo displayInfo) {
        Size size = displayInfo.getSize();
        return "^ 10 " + size.getWidth() + " " + size.getHeight() + " 255\n" + "$ 255";
    }

    public static void main(String[] args) {
        InputThread input = new InputThread(STDIN, QUEUE);
        ControlThread control = new ControlThread(QUEUE, CONTROLLER);
        System.out.println(new App().getGreeting(DISPLAY_MANAGER.getDisplayInfo(0)));
        input.start();
        control.run();
    }
}

