name: Android CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Copy file
        run: cp ./app/build/outputs/apk/release/app-release-unsigned.apk ./maatouch

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maatouch
          path: ./maatouch
